services:
  - type: web
    name: taia-system-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: TG_WEBHOOK_SECRET
        generateValue: true
      - key: PAY_PROVIDER
        value: STARS
      - key: CRYPTO_TOKEN
        sync: false
      - key: MANAGER_URL
        value: https://t.me/taiastudio
